//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Dao
{
    using Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BookContext : DbContext
    {
        static BookContext()
        {
            Database.SetInitializer<BookContext>(null);
        }
        public BookContext() : base("name=BookContext")
        {
        }

        public BookContext(string connStr) : base(connStr)
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public IDbSet<UserEntity> Users { get; set; }
    }
}
